version: '3.8'
services:
  pg_test:
    image: postgres:15
    container_name: diplomas_pg_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diplomas_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d diplomas_test"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pg_test_data:/var/lib/postgresql/data
volumes:
  pg_test_data:
